spring:
  thymeleaf:
    cache: false   # 开发中设置为false，防止模板修改时的缓存
#  datasource:
#    url: jdbc:mysql://localhost/readinglist
#    username: dbuser
#    password: dbpass
#    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8443
  #https设置
#  ssl:
#    key-store: file://.....
#    key-store-password: letmein
#    key-password: letmein
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG

